/** Auto-generated by vite brandStamp plugin — do not edit. */
export const BRAND_V = "4e45f3f0fa07";
export const APP_BUILD_V = "7c1cb21ee118";
export const logoUrl = `/logo.png?v=${BRAND_V}`;
export const icon192Url = `/icon-192.png?v=${BRAND_V}`;
export const icon512Url = `/icon-512.png?v=${BRAND_V}`;
export const faviconUrl = `/favicon-64.png?v=${BRAND_V}`;
export const appleTouchIconUrl = `/apple-touch-icon.png?v=${BRAND_V}`;
export const manifestUrl = `/manifest.json?v=${BRAND_V}`;
