/** Auto-generated by vite brandStamp plugin — do not edit. */
export const BRAND_V = "d646e4643b77";
export const APP_BUILD_V = "7f9dc654fa64";
export const logoUrl = `/logo.png?v=${BRAND_V}`;
export const icon192Url = `/icon-192.png?v=${BRAND_V}`;
export const icon512Url = `/icon-512.png?v=${BRAND_V}`;
export const faviconUrl = `/favicon-64.png?v=${BRAND_V}`;
export const manifestUrl = `/manifest.json?v=${BRAND_V}`;
