/** Auto-generated by vite brandStamp plugin — do not edit. */
export const BRAND_V = "8e62aa32994b";
export const APP_BUILD_V = "221377830fc5";
export const logoUrl = `/logo.png?v=${BRAND_V}`;
export const icon192Url = `/gt-icon-192.png?v=${BRAND_V}`;
export const icon512Url = `/gt-icon-512.png?v=${BRAND_V}`;
export const faviconUrl = `/gt-favicon-64.png?v=${BRAND_V}`;
export const appleTouchIconUrl = `/gt-apple-touch-icon.png?v=${BRAND_V}`;
export const manifestUrl = `/manifest.json?v=${BRAND_V}`;
